### PR TITLE
[RTM] Correctly parse column definition with comma

### LINKED ISSUE #723: Install tool cannot handle comma in default value
`varchar(255) NOT NULL default ','` will break the install tool.

Background information:
 - The install tool allows to execute each field update individually
 - The Doctrine schema tool reports one query for all fields (`ALTER TABLE tl_content ADD COLUMN foobar INT NULL, ADD COLUMN bar INT NULL`)

Due to this the install tool currently splits the query by comma and re-creates individual update queries. Which obviously fails if a comma is somewhere else than expected.

### PR DESCRIPTION
**Pull request by aschempp**
replaces #45, fixes contao/core-bundle#723

### CODE REVIEW

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Comment by leofeyer** [comment]
Actually merged in 7cb9c3cb635f4b57b4ad41a357e78c7146b5a38e into the correct branch.

**Comment by leofeyer** [comment]
It seems we need to adjust the minimum Composer versions to support `--prefer-lowest`:

https://travis-ci.org/contao/installation-bundle/jobs/211784206

Any idea what needs to be changed?

**Comment by aschempp** [comment]
Looks like the same issue we had recently, we should probably use `getMockForAbstractClass` instead of `getMock()`. Can you test that?

**Comment by leofeyer** [comment]
Does not work: https://travis-ci.org/contao/installation-bundle/jobs/213311737

**Comment by leofeyer** [comment]
Fixed in a2098f53dc01f97f5ebfed0c03a0b15b1a5e08fb now.

**Pull request merged**
