### PR TITLE
[WIP] Optionally handle tables without tl_ prefix

### PR DESCRIPTION
**Pull request by aschempp**
The solution is to add a table option `contao = true`. For an ORM annotation, it would look like this:

```php
/**
 * @ORM\Entity()
 * @ORM\Table(options={"contao"=true})
 */
class MyEntity
{
}
```

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
I don't like the implementation. We should handle all tables in the install tool instead, so we can stop using the `tl_` prefix in the future.

**Comment by leofeyer** [comment]
Regarding #48: @discordier @backbone87 @alnv IMO the install tool should handle all tables except for explicitly excluded tables (e.g. starting with `mm_` or `hoff_`). Would this be possible?

**Comment by backbone87** [comment]
I would be ok with Explicitly excluding tables, But then we cant use the schema filter, because it allows only for a single opaque regex

**Comment by aschempp** [comment]
> Regarding #48: @discordier @backbone87 @alnv IMO the install tool should handle all tables except for explicitly excluded tables (e.g. starting with mm_ or hoff_). Would this be possible?

This is a BC break for anyone that currently does anything in two tables. I agree that this is not best practice, but imagine running Piwik in the same table. There's no Contao extension that would exclude that table. It's not just about extensions…

**Comment by leofeyer** [comment]
> imagine running Piwik in the same table

This has never been a supported use case.

**Comment by aschempp** [comment]
Why not? I can perfectly have tables with `piwik_` in the same database?

**Comment by leofeyer** [comment]
In this case you could just add `piwik_` to the black list.

**Comment by aschempp** [comment]
Yeah I can do that, if I would have any idea how. I just don't see a point in a BC break if we can perfectly support it. And as @backbone87 pointed out the filtre is a regex so it's not extendable by bundles.

**Comment by leofeyer** [comment]
Let's discuss this in today's Mumble call.

**Comment by leofeyer** [comment]
@aschempp I guess this PR can be closed?

**Comment by aschempp** [comment]
I still like the idea and we might need it for when we add support for ORM, no?

**Pull request closed without merging**
