### PR TITLE
[RFC] Warm up the cache in the install tool

### LINKED ISSUE #63: CacheWarmup missing?
We use isotope with contao 4 and now we had several problems with missing dca-files in cache after cache:clear. then isotope cannot load the relations correctly (https://github.com/isotope/core/issues/1832).
after calling cache:warmup everything is fine because the cache is recreated.

so I researched in the code and found the 'cache_clearer' in the InstallationController. Now I understand, that after every Installation the problem occured.

Why is there no cache_warmer in the installation-bundle???

### PR DESCRIPTION
**Pull request by leofeyer**
This PR fixes #63.

### CODE REVIEW

**Comment by fritzmg** [comment]
Is there a specific reason not to use
```php
$this->container->get('cache_warmer')->warmUp($realCacheDir);
```
instead of executing the `cache:warmup` command via a PHP executable?

**Comment by leofeyer** [comment]
You can't just use `$this->container->get('cache_warmer')->warmUp($realCacheDir)`.

https://github.com/symfony/symfony/blob/3.3/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L138-L194

**Comment by fritzmg** [comment]
Hm, I see, the `cache:warmup` command does more than just `$warmer->warmUp($warmupDir);`.

However, wouldn't this change make Contao 4 (or at least the Install Tool) incompatible with some hosters where no proper PHP executable is available?

**Comment by Toflar** [comment]
I agree with @fritzmg. I think it should be done inline. More or less like so:

```php
$application = new Application($container->get('kernel'));
$application->setAutoExit(false);

$input = new ArrayInput([
    'command' => 'cache:clear',
    '--no-warmup',
    '-e' => $env
]);

$output = new NullOutput();
$application->run($input, $output);
```

**Comment by leofeyer** [comment]
It is impossible to do it "inline". There is a container already and until Symfony releases their rebootable container, we have to do it in a separate process.

**Comment by leofeyer** [comment]
@fritzmg Isn't `proc_open()` a requirement for the Contao Manager already?

**Comment by fritzmg** [comment]
I think so. However, take 1&1 for example. There you only have a PHP 5.5 command line interface available - and the cache warmup will fail with PHP 5.5 (as far as I tested). `composer update` or `install` will still work though (as long as you have the correct platform definition in your `composer.json`).

(Which also means that on 1&1 there is currently no way to build the internal cache of Contao 4.)

**Comment by leofeyer** [comment]
Contao 4.4 requires at least PHP 5.6.

**Comment by fritzmg** [comment]
1&1 supports PHP 7.1. But the CLI is (stupidly) limited to PHP 5.5.

**Comment by fritzmg** [comment]
I tried the changes on a 1&1 Basic account (not the most ideal environment for Contao 4 anyway) and the processes created by `new Process` simply run into a timeout there:
```
[2017-08-12 14:26:04] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessTimedOutException(code: 0): 
The process \"/usr/bin/php […]/vendor/bin/contao-console cache:clear --no-warmup -e prod\" exceeded the timeout of 60 seconds. at […]/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php:1332)"} []
```
In fact, any process does not seem to finish at all. Even if I do something as simple as
```php
$process = new Process("php -v");
$process->run();
```
the process will time out.

Furthermore, the path returned by the `PhpExecutableFinder` is `/usr/bin/php`. But this default path is only PHP 4.4.9 on 1&1 (any account, presumably):
```
PHP 4.4.9 (cgi-fcgi) (built: Feb 28 2017 11:31:58)
Copyright (c) 1997-2008 The PHP Group
Zend Engine v1.3.0, Copyright (c) 1998-2004 Zend Technologies
```
I don't think the `PhpExecutableFinder` will be able to find the most suitable PHP executable by itself? Isn't that the reason why the PHP executables need to be set manually per hoster in the Contao Manager as well? (See https://github.com/contao/contao-manager/blob/develop/api/Resources/config/providers.yml)

**Comment by leofeyer** [comment]
Ok, fixed in 203b5ddb87d97ce570f7942a489aa6c769684d15 then. The solution implies a couple of limitations (e.g. we can only warm up the cache of the current environment), but at least it does not require a separate process. Hopefully, we can improve this with Symfony 3.4.

**Pull request closed without merging**
